# Generated by Django 5.0.1 on 2024-01-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='returned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
